### ISSUE TITLE
Identical Scheduled Transactions - How to get their ScheduleID

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#316]
From some version of the SDK, when you submit an identical scheduled transaction and you get its receipt, it resolves with `exceptional receipt status: IDENTICAL_SCHEDULE_ALREADY_CREATED`. How exactly do you now have to get the ScheduleID of the original transaction, since the whole receipt is empty?

**Comment by failfmi** [comment]
The receipt should return the ScheduleID of the original transaction.

**Comment by failfmi** [comment]
https://github.com/hashgraph/hedera-protobufs/blob/main/services/schedule_create.proto#L59

**Comment by danielakhterov** [comment]
Not sure how that happened, but this was fixed at one point and is now back. Nonetheless, definitely a bug. cc @andrix10 `TransactionReceipt` should be filled out even if the executing fails. Provided, of course, the execution failed with a Hedera Services response code and not a gRPC error.

**Comment by failfmi** [comment]
The version that this works, when you get the receipt, it does not resolve with an error, and the receipt itself contains the correct status `hedera.StatusIdenticalScheduleAlreadyCreated`, the scheduleID and the transaction ID of the original one.

**Comment by danielakhterov** [comment]
I do remember that, and I think that is maybe why this issue has been brought back to life. The receipt itself should still be empty, but there is another receipt in the error which should not be empty. The reason we went with this design is because it is consistent with the other SDKs (although it is definitely a bit weird for Go).

**Comment by SimiHunjan** [comment]
Can you please update to v2.5.0 to see if this has been resolved?

**Comment by danielakhterov** [comment]
Closing as I think this is now resolved.

**Comment by failfmi** [comment]
The previous behaviour was that error would not be returned, only the receipt.

**Comment by failfmi** [comment]
This is not fixed, because the error you receive is not a precheck.

**Comment by danielakhterov** [comment]
Released part of https://github.com/hashgraph/hedera-sdk-go/releases/tag/v2.5.1
